### ISSUE TITLE
Can't run the code on custom data

### ISSUE THREAD

**Issue by realfolkcode** [fseiffarth/GCoreApproximation#1]
Hello! I am trying to compute the convex hulls of random sets on custom data. To do this, I first put my edge list (*.txt) into the GraphData folder. Then, I ran the following two executables:

`./ConvertGraphs`

`./ExpApproxCore -i ../../GraphData/ --generators 4 --threshold 0.01 --threads 1 --outer_loop 0 --save_load_samples --no_tree --no_core --file_name large_graphs`

The second executable yields: 
`*** Error: Execution stopped: IsNode(SrcNId) && IsNode(DstNId) [Reason:'84424 or 85420 not a node.'], file /content/ExternalLibraries/Snap-6.0/snap-core/graph.cpp, line 93`

It seems to work on some graphs (i.e., CA-AstroPh from SNAP) and fail on others.

GCC version: 9.4.0

**Comment by realfolkcode** [comment]
Here is an example of the edge list: https://pastebin.com/Kb0bDbrQ
This graph has 183 nodes

**Comment by fseiffarth** [comment]
The issue was based on a missing relabeling of node ids. It is fixed with the latest commits.
